config/routes.rb
Rails.application.routes.draw do
  resources :proposals
  root 'proposals#index'
  match '/twitter_search', to: 'twitter#search_users', via: 'get'
  match '/add_proposal', to: 'twitter#add_proposal', via: 'post', as: 'add_proposal'
  match '/twitter_proposal', to: 'twitter#twitter_proposal',     via: 'get'
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  def send_to_codea
      api_token = Rails.application.secrets.codea_api_token
      url = "http://codea-codigox.herokuapp.com/api_create"
      params = {"api_token" => api_token,
                "proposal[name]"=> self.name,
                "proposal[avatar]" => self.avatar,
                "proposal[twitter_handle]" => self.twitter_handle}
      Net::HTTP.post_form(URI.parse(url), params)
  end

  def counter_codea
      api_token = Rails.application.secrets.codea_api_token
      url = "http://codea-codigox.herokuapp.com/api_counter"
      params = {"api_token" => api_token,
                "proposal[twitter_handle]" => self.twitter_handle}
      Net::HTTP.post_form(URI.parse(url), params)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("https://mexico.numa.co/wp-content/uploads/sites/8/2016/05/logo_NUMA_kleinblue.png",
      alt: "Numa", :height => 32),
      root_path,
      class: "navbar-brand logo both-logos",
      id: "logo_tag" %>
      <%= link_to image_tag("https://codealab.files.wordpress.com/2016/07/codeacamp_logo.png",
                    alt: "Codea", :height => 32),
                    root_path,
                    class: "navbar-brand logo pull-right both-logos",
                    id: "logo_codea" %>
    <div class="collapse navbar-collapse" id="main-menu" >
      <ul class="nav navbar-nav">
        <li><%= link_to "Propón con Twitter", twitter_proposal_path %></li>
        <li><%= link_to "Propuestas", proposals_path %></li>
        <li><%= link_to "Nueva propuesta", new_proposal_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codea - Numa</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>

  <div class="container-fluid">
    <div id="flash_div">
      <% flash.each do |key, value| %>
      <div class="col-md-12 col-sm-12 col-xs-12 form-group flash_message">
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      </div>
      <% end %>
    </div>

    <%= yield %>
  </div>
</body>
</html>

app/views/twitter/_users.html.erb
<div class="container">
  <div class="row">
    <% users.each do |user| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail thumbnail-fix">
          <%= image_tag user.profile_image_url.to_s.gsub!("_normal", "_bigger"), class: "pull-left username-card-img" %>
          <div class="caption">
            <h5 class="text-center username-card" style="display:inline-block"><%= user.name %></h5>
            <!-- <p><a href="#" class="btn btn-primary" role="button">Button</a></p> -->
            <%= form_for Proposal.new, url: add_proposal_path, method: :post do |f| %>
              <%= f.hidden_field :name, value: user.name%>
              <%= f.hidden_field :avatar, value: user.profile_image_url %>
              <%= f.hidden_field :twitter_handle, value: user.screen_name  %>
              <%= button_tag(type: 'submit', class: "btn btn-primary btn-xs") do %>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/twitter/search_users.js.erb
<% if @users.empty? %>
  $('#search_results').html("<h4 class='text-center'>No se encontro nada!</h4><br><img class='center-block'src='https://s14.postimg.org/b58ap0koh/cryingcomputer.gif'>");
<% else %>
  $('#search_results').html("<%= j render('users', users: @users) %>");
<% end %>

app/views/twitter/twitter_proposal.html.erb
<div id="first_section">
  <div class="row first-row">
    <h1 class="title text-center" id="speaker-title">¿Cuál es tu propuesta de Speaker?</h1>
    <%= form_tag twitter_search_path, method: "get", remote: true, class: "form-horizontal" do %>
      <div class="col-md-offset-3 col-md-6 col-xs-12">
        <div class="input-group form-group-lg">
          <div class="input-group-addon">@</div>
          <%= text_field :twitter, :search, class: "form-control", placeholder: "Usuario de Twitter" %>
          <span class="input-group-btn">
            <%= button_tag "Search" , class: "btn btn-lg btn-primary" %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</div><!-- first_section -->
<div id="search_results" class="row"></div>